global using TimesheetAutomation.App.Configurations;
global using Newtonsoft.Json;
global using TimesheetAutomation.App.Services;
global using TimesheetAutomation.App.Interfaces;
global using OpenQA.Selenium.Chrome;
global using TimesheetAutomation.App.Utils;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Support.UI;
global using SeleniumExtras.WaitHelpers;
global using DriverService = TimesheetAutomation.App.Services.DriverService;
global using System.Net.NetworkInformation;